# Exploring Hacker News Post Data
Within this code I am exploring the hacker_news.csv which is provided by dataquest.

In [1]:
from csv import reader
file_open = open('hacker_news.csv')
file_read = reader(file_open)
hacker_list = list(file_read)
headers = hacker_list[0]
hn = hacker_list[1:]
for i in hn[:5]:
    print(i)

['12224879', 'Interactive Dynamic Video', 'http://www.interactivedynamicvideo.com/', '386', '52', 'ne0phyte', '8/4/2016 11:52']
['10975351', 'How to Use Open Source and Shut the Fuck Up at the Same Time', 'http://hueniverse.com/2016/01/26/how-to-use-open-source-and-shut-the-fuck-up-at-the-same-time/', '39', '10', 'josep2', '1/26/2016 19:30']
['11964716', "Florida DJs May Face Felony for April Fools' Water Joke", 'http://www.thewire.com/entertainment/2013/04/florida-djs-april-fools-water-joke/63798/', '2', '1', 'vezycash', '6/23/2016 22:20']
['11919867', 'Technology ventures: From Idea to Enterprise', 'https://www.amazon.com/Technology-Ventures-Enterprise-Thomas-Byers/dp/0073523429', '3', '1', 'hswarna', '6/17/2016 0:01']
['10301696', 'Note by Note: The Making of Steinway L1037 (2007)', 'http://www.nytimes.com/2007/11/07/movies/07stein.html?_r=0', '8', '2', 'walterbell', '9/30/2015 4:12']


In [2]:
ask_posts, show_posts, other_posts = [], [], []

for i in hn:
    title = i[1]
    if title.lower().startswith('ask hn'):
        ask_posts.append(i)
    if title.lower().startswith('show hn'):
        show_posts.append(i)
    else:
        other_posts.append(i)
print(len(ask_posts), len(show_posts), len(other_posts))

1744 1162 18938


In [3]:
print(ask_posts[:5])
print(show_posts[:5])

[['12296411', 'Ask HN: How to improve my personal website?', '', '2', '6', 'ahmedbaracat', '8/16/2016 9:55'], ['10610020', 'Ask HN: Am I the only one outraged by Twitter shutting down share counts?', '', '28', '29', 'tkfx', '11/22/2015 13:43'], ['11610310', 'Ask HN: Aby recent changes to CSS that broke mobile?', '', '1', '1', 'polskibus', '5/2/2016 10:14'], ['12210105', 'Ask HN: Looking for Employee #3 How do I do it?', '', '1', '3', 'sph130', '8/2/2016 14:20'], ['10394168', 'Ask HN: Someone offered to buy my browser extension from me. What now?', '', '28', '17', 'roykolak', '10/15/2015 16:38']]
[['10627194', 'Show HN: Wio Link  ESP8266 Based Web of Things Hardware Development Platform', 'https://iot.seeed.cc', '26', '22', 'kfihihc', '11/25/2015 14:03'], ['10646440', 'Show HN: Something pointless I made', 'http://dn.ht/picklecat/', '747', '102', 'dhotson', '11/29/2015 22:46'], ['11590768', 'Show HN: Shanhu.io, a programming playground powered by e8vm', 'https://shanhu.io', '1', '1', 'h

In [4]:
total_ask_comments = 0
for i in ask_posts:
    total_ask_comments += int(i[4])
avg_ask_comments = total_ask_comments/len(ask_posts)
print(avg_ask_comments)

total_show_comments = 0
for i in show_posts:
    total_show_comments += int(i[4])
avg_show_comments = total_show_comments/len(show_posts)
print(avg_show_comments)

14.038417431192661
10.31669535283993


It seems ask_posts receives more comments per post on average than show posts. Maybe this is due to the fact that ask posts require some sort of community engagement in terms of writing comments rather than, a post about a product would receive. I would like to compare the overral reactions, or likes that show_posts receive to see which receives more community involvement.

In [5]:
import datetime as dt
result_list = []

for i in ask_posts:
    result_list.append([i[6], int(i[4])])

counts_by_hour = {} 
comments_by_hour = {}

for i in result_list:
    time = i[0]
    first = dt.datetime.strptime(time, '%m/%d/%Y %H:%M')
    hour = first.strftime('%H')
    if hour not in counts_by_hour and hour not in comments_by_hour:
        counts_by_hour[hour] = 1
        comments_by_hour[hour] = i[1]
    else:    
        counts_by_hour[hour] += 1
        comments_by_hour[hour] += i[1]
print(counts_by_hour, '\n')
print(comments_by_hour)

{'09': 45, '13': 85, '10': 59, '14': 107, '16': 108, '23': 68, '12': 73, '17': 100, '15': 116, '21': 109, '20': 80, '02': 58, '18': 109, '03': 54, '05': 46, '19': 110, '01': 60, '22': 71, '08': 48, '04': 47, '00': 55, '06': 44, '07': 34, '11': 58} 

{'09': 251, '13': 1253, '10': 793, '14': 1416, '16': 1814, '23': 543, '12': 687, '17': 1146, '15': 4477, '21': 1745, '20': 1722, '02': 1381, '18': 1439, '03': 421, '05': 464, '19': 1188, '01': 683, '22': 479, '08': 492, '04': 337, '00': 447, '06': 397, '07': 267, '11': 641}


In [6]:
avg_by_hour = []
for i in counts_by_hour:
    avg_by_hour.append([i, comments_by_hour[i]/counts_by_hour[i]])
print(avg_by_hour)

[['09', 5.5777777777777775], ['13', 14.741176470588234], ['10', 13.440677966101696], ['14', 13.233644859813085], ['16', 16.796296296296298], ['23', 7.985294117647059], ['12', 9.41095890410959], ['17', 11.46], ['15', 38.5948275862069], ['21', 16.009174311926607], ['20', 21.525], ['02', 23.810344827586206], ['18', 13.20183486238532], ['03', 7.796296296296297], ['05', 10.08695652173913], ['19', 10.8], ['01', 11.383333333333333], ['22', 6.746478873239437], ['08', 10.25], ['04', 7.170212765957447], ['00', 8.127272727272727], ['06', 9.022727272727273], ['07', 7.852941176470588], ['11', 11.051724137931034]]


In [7]:
swap_avg_by_hour = []
for i in avg_by_hour:
    swap_avg_by_hour.append([i[1], i[0]])
print(swap_avg_by_hour)

[[5.5777777777777775, '09'], [14.741176470588234, '13'], [13.440677966101696, '10'], [13.233644859813085, '14'], [16.796296296296298, '16'], [7.985294117647059, '23'], [9.41095890410959, '12'], [11.46, '17'], [38.5948275862069, '15'], [16.009174311926607, '21'], [21.525, '20'], [23.810344827586206, '02'], [13.20183486238532, '18'], [7.796296296296297, '03'], [10.08695652173913, '05'], [10.8, '19'], [11.383333333333333, '01'], [6.746478873239437, '22'], [10.25, '08'], [7.170212765957447, '04'], [8.127272727272727, '00'], [9.022727272727273, '06'], [7.852941176470588, '07'], [11.051724137931034, '11']]


I have assorted in the list in descending order. I have found that the max value of average comments would be at 3pm. This would make sense because many people have down time around 3pm. Kids getting out of school, adults day is winding down, some people even take lunch break at this late of hour. So the site probably peaks in usage at this time making more comment available to occur.

In [8]:
sorted_swap = sorted(swap_avg_by_hour, reverse=True)
print('Top 5 Hours for Ask Posts Comments')
for i in sorted_swap[:5]:
    first = dt.datetime.strptime(i[1], '%H')
    time_format = first.strftime('%H:%M')
    print('{0}: {1:.2f} average comments per post.'.format(time_format, i[0]))

Top 5 Hours for Ask Posts Comments
15:00: 38.59 average comments per post.
02:00: 23.81 average comments per post.
20:00: 21.52 average comments per post.
16:00: 16.80 average comments per post.
21:00: 16.01 average comments per post.


In [9]:
print(headers)

['id', 'title', 'url', 'num_points', 'num_comments', 'author', 'created_at']


In this next segment of code I am going to determine the number of points received both both ask and show posts, and which one receives the most points. Then from that, I will gather which one receives the most points and determine at which times the most points would be received.

In [10]:
tot_avg_ask = 0
tot_avg_show = 0

for i in ask_posts:
    tot_avg_ask += int(i[3])
for i in show_posts:
    tot_avg_show += int(i[3])

tot_avg_ask = tot_avg_ask/len(ask_posts)
tot_avg_show = tot_avg_show/len(show_posts)

print(tot_avg_ask, tot_avg_show)

15.061926605504587 27.555077452667813


It seems I was correct in my assumption in that show_posts would receive more like on average than ask_posts would receive. From here I will determine for show_posts at what times per hour the most likes would be received.

In [11]:
point_per_hour = {}
count_per_hour = {}
print(len(show_posts))
for i in show_posts:
    dat = dt.datetime.strptime(i[6], '%m/%d/%Y %H:%M')
    here = dat.strftime('%H')
#    print(here)
    if here in point_per_hour and here in count_per_hour:
        count_per_hour[here] += 1
        point_per_hour[here] += int(i[4])
#        print(i[4])
        continue
    count_per_hour[here] = 1
    point_per_hour[here] = int(i[4])
print(point_per_hour)
print(count_per_hour)

1162
{'14': 1156, '22': 570, '18': 962, '07': 299, '20': 612, '05': 58, '16': 1084, '19': 539, '15': 632, '03': 287, '17': 911, '06': 142, '02': 127, '13': 946, '08': 165, '21': 272, '04': 247, '11': 491, '12': 720, '23': 447, '09': 291, '01': 246, '10': 297, '00': 487}
{'14': 86, '22': 46, '18': 61, '07': 26, '20': 60, '05': 19, '16': 93, '19': 55, '15': 78, '03': 27, '17': 93, '06': 16, '02': 30, '13': 99, '08': 34, '21': 47, '04': 26, '11': 44, '12': 61, '23': 36, '09': 30, '01': 28, '10': 36, '00': 31}


Now that I have the values for the number of posts per hour, and the total number of like per hour. I will now formulate a data structure that will have the average number of likes per hour.

In [12]:
tot_dict = {}
lis_avg = []
for i in point_per_hour:
    lis_avg.append([(point_per_hour[i]/count_per_hour[i]), i])
fin_lis = sorted(lis_avg, reverse=True)

print('Top 5 Average Likes Per Show Posts')
for i in fin_lis[:5]:
    thanks = dt.datetime.strptime(i[1], '%H')
    thanks = thanks.strftime('%H:%M')
    print('{0}: {1:.2f} average points per post per hour.'.format(thanks, i[0]))

Top 5 Average Likes Per Show Posts
18:00: 15.77 average points per post per hour.
00:00: 15.71 average points per post per hour.
14:00: 13.44 average points per post per hour.
23:00: 12.42 average points per post per hour.
22:00: 12.39 average points per post per hour.


From this data we can conclude that likes per hour is most accumulated when the post is at 6pm.

In [13]:
com_point = []
print(headers)
for i in other_posts:
        com_point.append([i[3], i[4], i[6]])
print(com_point)

['id', 'title', 'url', 'num_points', 'num_comments', 'author', 'created_at']
[['386', '52', '8/4/2016 11:52'], ['39', '10', '1/26/2016 19:30'], ['2', '1', '6/23/2016 22:20'], ['3', '1', '6/17/2016 0:01'], ['8', '2', '9/30/2015 4:12'], ['53', '22', '10/31/2015 9:48'], ['3', '4', '11/13/2015 0:45'], ['2', '6', '8/16/2016 9:55'], ['34', '7', '3/22/2016 16:18'], ['91', '10', '10/13/2015 9:30'], ['3', '1', '3/27/2016 18:08'], ['2', '1', '5/10/2016 4:46'], ['18', '14', '6/26/2016 16:36'], ['59', '18', '4/28/2016 10:01'], ['7', '5', '8/22/2016 12:37'], ['1', '2', '4/1/2016 9:45'], ['28', '29', '11/22/2015 13:43'], ['109', '116', '1/4/2016 18:58'], ['1', '1', '7/19/2016 12:05'], ['1', '2', '2/11/2016 12:57'], ['68', '13', '1/31/2016 20:38'], ['1', '1', '5/2/2016 10:14'], ['11', '2', '12/10/2015 18:58'], ['170', '112', '1/27/2016 3:47'], ['15', '4', '7/2/2016 22:08'], ['115', '106', '12/15/2015 17:56'], ['1', '2', '2/26/2016 14:35'], ['234', '100', '2/23/2016 18:41'], ['4', '1', '12/18/2015 20:

I made a list holding the times, number or points, and number of comments each post has in other posts. From here I will separate the number of posts per hour and the individual points and comments to individual dictionaries

In [14]:
com_dict = {}
point_dict = {}
count_dict = {}

for i in com_point:
    time = dt.datetime.strptime(i[2], '%m/%d/%Y %H:%M')
    time = time.strftime('%H')
    # only need to compare one dict because all have same keys
    if time in com_dict:
        com_dict[time] += int(i[1])
        point_dict[time] += int(i[0])
        count_dict[time] += 1
        continue
    com_dict[time] = int(i[1])
    point_dict[time] = int(i[0])
    count_dict[time] = 1

print(com_dict, '\n')
print(point_dict, '\n')
print(count_dict, '\n')

{'11': 20173, '19': 27355, '22': 18114, '00': 16991, '04': 11290, '09': 14983, '16': 29773, '18': 30625, '10': 16521, '12': 24631, '13': 29616, '20': 22802, '03': 11339, '17': 33873, '14': 32389, '01': 12219, '23': 17135, '08': 13897, '02': 13635, '21': 22380, '15': 35177, '06': 9111, '05': 10232, '07': 12277} 

{'11': 38820, '19': 60324, '22': 38590, '00': 36169, '04': 22938, '09': 29131, '16': 62177, '18': 60200, '10': 36848, '12': 46069, '13': 59460, '20': 42369, '03': 23541, '17': 69718, '14': 60473, '01': 26003, '23': 35649, '08': 27345, '02': 26579, '21': 44870, '15': 66443, '06': 19455, '05': 19939, '07': 25822} 

{'11': 718, '19': 1090, '22': 829, '00': 666, '04': 501, '09': 579, '16': 1209, '18': 1193, '10': 650, '12': 862, '13': 1003, '20': 991, '03': 461, '17': 1269, '14': 1065, '01': 560, '23': 742, '08': 544, '02': 499, '21': 983, '15': 1156, '06': 452, '05': 434, '07': 482} 



I have assorted each dictionary for points accumlated per hour, comments accumlated per hour, and the total number of posts per hour. From here I will obtain the average number of points and comments per hour. Then compare them to show_posts and ask_posts in accordance to which have the most comments and points.

In [16]:
avg_com_other = []
avg_point_other = []
for i in com_dict:
    avg_com_other.append([com_dict[i]/count_dict[i], i])
    avg_point_other.append([point_dict[i]/count_dict[i], i])
final_com = sorted(avg_com_other, reverse=True)
final_point = sorted(avg_point_other, reverse=True)

print('Top 5 Comments per Hour for Other Posts:')
for i in final_com[:5]:
    here = dt.datetime.strptime(i[1], '%H')
    here = here.strftime('%H:%M')
    print('{0}: {1:.2f} average comments per post per hour.'.format(here, i[0]))
print('\nTop 5 Comments per Hour for Other Posts:')
for i in final_point[:5]:
    here = dt.datetime.strptime(i[1], '%H')
    here = here.strftime('%H:%M')
    print('{0}: {1:.2f} average points per post per hour.'.format(here, i[0]))
print('\n', )
print(len(other_posts), len(ask_posts), len(show_posts))

Top 5 Comments per Hour for Other Posts:
15:00: 30.43 average comments per post per hour.
14:00: 30.41 average comments per post per hour.
13:00: 29.53 average comments per post per hour.
12:00: 28.57 average comments per post per hour.
11:00: 28.10 average comments per post per hour.

Top 5 Comments per Hour for Other Posts:
13:00: 59.28 average points per post per hour.
15:00: 57.48 average points per post per hour.
14:00: 56.78 average points per post per hour.
10:00: 56.69 average points per post per hour.
19:00: 55.34 average points per post per hour.


18938 1744 1162


It seems Other Posts overall has more points on average compared to ask and show posts, but less comments than ask posts on average.
Show posts had more overall points compared to ask, so I will only use that data to compare: 18:00: 15.77 average points per post per hour.
Show posts only had 15.77 average points while other posts had 59.28 average points per hour. This may be due to the fact that other posts has 18,938 posts and show only has 1,162.
Ask posts had 38.59 comements per hour while Other Posts had 30.43. This is probably due to the fact that ask posts require more comments within the community rather than other posts.

# Conclusion
Overall we see ask posts thrive in terms of comments, and other posts in terms of points. It is surprising to see show posts have such little like in comparison to Other posts data, but I found this may be due to there being 18,938 posts in comparison to show posts 1,162. All three showed posts should be around 3pm in terms of getting the most points, and comments. This may be due to the fact this is downtime in a lot of students, workers, etc. days. All in all we can conclude that in order to get the most likes and points we should post under other posts and post around 3pm.